### ISSUE TITLE
Bug calendario de notificaciones

### ISSUE THREAD

**Issue by iLestar** [sena-proyectos/Siscomite#17]
## Cambio de meses

Hay un pequeño bug al cambiar de mes en el calendario,  si te vas a un mes diferente, sea uno posterior o anterior, este te seguirá marcando el día
![imagen](https://github.com/sena-proyectos/Siscomite/assets/71247432/a750f1e7-51c6-4d26-ba8b-256c48344063)
Como se puede ver en la imagen anterior, se ve como queda Octubre 25, cosa que no es correcta.

---
![firefox_ioTOdAw8CB](https://github.com/sena-proyectos/Siscomite/assets/71247432/0cc9ae69-b5a9-40bd-ac58-c622174e1722)

**Comment by Tattoarco** [comment]
Oks, ya lo he solucionado


<img width="193" alt="Captura de pantalla 2023-09-27 112119" src="https://github.com/sena-proyectos/Siscomite/assets/136488893/7d4f7b95-f481-4ff3-abf8-f320c7bd90cc">
<img width="197" alt="Captura de pantalla 2023-09-27 112135" src="https://github.com/sena-proyectos/Siscomite/assets/136488893/5136b50b-e25d-4289-8407-2500bd8d6eab">
