### ISSUE TITLE
Vista de generar carta de citación no se ajusta a los distintos tipos de pantalla, realiza scroll horizontal y vertical 

### ISSUE THREAD

**Issue by Tattoarco** [sena-proyectos/Siscomite#22]
<img width="960" alt="image" src="https://github.com/sena-proyectos/Siscomite/assets/136488893/73409fdf-0471-4163-955f-0b763d64a068">

**Comment by STBenji** [comment]
Mi trabajo no se basa en hacer responsive el aplicativo
